name: cpplint
on:
  schedule:
    # Every day on midnight UTC
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: ./tools/check_style.sh
