name: cpplint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: ./tools/check_style.sh
